# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy to MoeLTY SaaS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run generate
  
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    concurrency: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Push Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: service_lxfe
        key: ${{ secrets.SSH_KEY }}
        source: dist
        target: ~/deploys/${{ github.sha }}
        strip_components: 1
    - name: Switch to New Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: service_lxfe
        key: ${{ secrets.SSH_KEY }}
        script: ln -sfn ~/deploys/${{ github.sha }} ~/www
